### ISSUE TITLE
基于您的基础，我又做了一波更新

### ISSUE THREAD

**Issue by cxlcym** [alaskasquirrel/Chinese-Podcasts#6]
Update1.29

日谈公园：Grover Podcast 市场直接检索“日谈公园” 即可。

Update2.22

食色性STUDIO：https://music.163.com/#/radio/?id=333282051&userid=109123524

Update4.18

App 推荐（安卓/ISO）： MoonFM ： https://moon.fm/  

Update6.15

鉴于Google的Chrome（移动端）已内置了PodCast，那再来波更新，经个人实践为目前最为方便、最好用：

1.Googleplay下载安装：“Google语音搜索”、“Google播客”

2.节目（直接搜索订阅）：

婊酱 | Bitch Up 

科技岛读

偷先生恋爱法

马力欧陪你喝一杯

老马侃美国

转角国际·重磅广播

大人的Small Talk

九八新闻台

百灵果NEWS

到海外去

人间指南

讲东讲西

**Comment by alaskasquirrel** [comment]
本项目中播客的收录，在我心中是有一套准则的。
如果你也是一位播客爱好者，不妨创建属于你的项目。
感谢，你的关注！
