### ISSUE TITLE
建议：是否可以考虑下添加一个新的分类——开源呢

### ISSUE THREAD

**Issue by LinuxSuRen** [alaskasquirrel/Chinese-Podcasts#9]
这里有部分开源相关的播客 https://github.com/opensource-f2f/episode#%E6%9B%B4%E5%A4%9A%E5%BC%80%E6%BA%90%E7%9B%B8%E5%85%B3%E7%9A%84%E9%9F%B3%E8%A7%86%E9%A2%91%E8%8A%82%E7%9B%AE

**Comment by alaskasquirrel** [comment]
感谢你的分享！
